In [ ]:
"""5 friends decided to go for a picnic and they start discussing the items which they have to take with
them. They wanted to create a list where they can add items one by one. To help them, write a
program in python to create an empty list. Then use for loop and append() method to add items one by
one. ( Note: Range of loop depends on the number of items that have to be included in the list.) After
adding all the items ask whether the user whether wants to remove any items or not and then print the
whole list on the screen."""

In [37]:
item = []

add_items = int(input("ENTER NUMBER OF ITEMS WANT TO ADD:-"))
for i in range(add_items):
  item_name = input("ENTER NAME OF ITEMS:-")
  item.append(item_name)

print("TYPE 1 To ADD ITEMS")
print("TYPE 2 TO REMOVE ITEMS")
remove_item = int(input("INPUT:-"))
if remove_item == 1:
    print("PLEASE ADD ITEM NAME")
    item_name.update()
    print(item)
elif remove_item == 2:
    print("PLEASE REMOVE THE ITEM NAME")
    item.remove()
    print(item)
else:
    print("YOU HAVE ENTER WRONG NUMBER")

ENTER NUMBER OF ITEMS WANT TO ADD:-2
ENTER NAME OF ITEMS:-water
ENTER NAME OF ITEMS:-clothes
TYPE 1 To ADD ITEMS
TYPE 2 TO REMOVE ITEMS
INPUT:-2
PLEASE REMOVE THE ITEM NAME

TypeError: list.remove() takes exactly one argument (0 given)

In [ ]:

'''A teacher created a list of names of the students. Now teachers want to get the name of all those
students whose name starts with the letter “A”. To help the teacher write a python program and create
a list of names of students. Then print the names which start with the letter “A”. (Hint: Use for loop and
give condition I [0] == “A” )'''

In [23]:
name = ["ARJUN","AMRAJ","CHIKU","PAPU","ALPHESH","ALPHA","RAJU","ATMARAM"]
for x in name:
  if x [0] == "A":
    print("YOUR TOTAL NUMBER OF NAME START WITH A:-", x)

YOUR TOTAL NUMBER OF NAME START WITH A:- ARJUN
YOUR TOTAL NUMBER OF NAME START WITH A:- AMRAJ
YOUR TOTAL NUMBER OF NAME START WITH A:- ALPHESH
YOUR TOTAL NUMBER OF NAME START WITH A:- ALPHA
YOUR TOTAL NUMBER OF NAME START WITH A:- ATMARAM

In [ ]:
'''in a class, the teacher decides to assign roll numbers to the students in alphabetical order of their
names. The class consists of more than 60 students. So the class monitor decides to create a list in
python to take the name of the students in any order and then will print the list in sorted order with roll
numbers. ( Hint: use append() method to add the names in the list and then use sort() function on the
list ) . After sorting the list, the Index number of the list can be used to assign the roll numbers to the
students. ( Hint : roll no = index + 1 )
'''

In [44]:
rollno = 0
name = []

enter_name = input("ENTER NAME of STUDENTS:-")
name.append(enter_name)
name.sort("A")

rollno = rollno + 1
print(rollno, name)

ENTER NAME of STUDENTS:-a

TypeError: 'list' object cannot be interpreted as an integer

In [ ]:
'''Nidhi is trying to solve a few questions in mathematics. She is actually finding out the central tendency(
mean, median, and mode ) of some numbers. It is taking a lot of time for her to complete the
questions. Help Nidhi in solving the following questions. Write the program for each of them.
● .
● She wants to find the mean of numbers. Write a program to find the mean of numbers.
● Hint: find the sum of all the numbers in the list then divide it with the number of elements present in the
list.
● .
● Shen wants to find the median as well. Write a program to find the median of numbers in the given list.
● Hint: Sort the entire list the print the middle value of the list. If the list contains n numbers where n is
even, then find the mean of the middle values.
● .
● Lastly, she wants to find the mode of numbers. To help Nidhi in this problem, write a program in python
where users can enter n numbers as input, and then the program will print the mode of numbers.
● Hint: Print the number having maximum count in the list.'''

In [45]:
'''In a school, a football competition is going to be held. The sports captain needs to create a list of the
players with their heights. According to the rule, only those students can participate in the competition
who have a height greater than 167cm. To make things easier write a python program. Create a list of
tuples with the name of the player and their height in cm. Note: while taking the input from the users,
don’t include the players whose height is less than 167cm. ( Use continue statement )
● Sample list: [ (“Chris” , 170) , (“Aditya” , 182) , (“Chirag” , 176 ) ]'''

'In a school, a football competition is going to be held. The sports captain needs to create a list of the\nplayers with their heights. According to the rule, only those students can participate in the competition\nwho have a height greater than 167cm. To make things easier write a python program. Create a list of\ntuples with the name of the player and their height in cm. Note: while taking the input from the users,\ndon’t include the players whose height is less than 167cm. ( Use continue statement )\n● Sample list: [ (“Chris” , 170) , (“Aditya” , 182) , (“Chirag”\xa0,\xa0176\xa0)\xa0]'

In [51]:
name=[]


add_name = input("ENTER NAME OF PLAYER:-")
for i in range(add_name):

  height = int(input("ENETR HEIGHT:-"))

if height >= 167:
  name.append((name.height))
  name = name + 1
else:
  print("WRONG")


print(name)

ENTER NAME OF PLAYER:-ram
ENETR HEIGHT:-170

TypeError: can only concatenate tuple (not "int") to tuple